# Generated by scripts/update.sh from the v0.0.3-main.3 release; do not edit by hand.
class Accel < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/mesutoezdil/accel"
  version "0.0.3-main.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.3-main.3/accel-darwin-arm64"
      sha256 "5f4271fcd7e9687caa103dc7b75e99d7cdda6b9e8b5a978c28397a5a8f25c72d"
    end
    on_intel do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.3-main.3/accel-darwin-amd64"
      sha256 "456eee6572298e131cd05e17d9ff213c6e63a88d4893db05e6a776d4136feb0d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.3-main.3/accel-linux-arm64"
      sha256 "8186300c6ebdee9e774e1a05ec71e94a6c5d54e828b3db6333cff0a806c651a0"
    end
    on_intel do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.3-main.3/accel-linux-amd64"
      sha256 "305728323a9d1f878fda06137da3069621245985a7c606d113aedbdc51adbd9d"
    end
  end

  def install
    binary = Dir["accel-*"].first
    chmod 0755, binary
    bin.install binary => "accel"
    generate_completions_from_executable(bin/"accel", "--completion")
    (man1/"accel.1").write Utils.safe_popen_read(bin/"accel", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/accel --version")
    assert_match "accel", shell_output("#{bin}/accel --demo --once")
  end
end
