# Generated by scripts/update.sh from the v0.0.25-main.1 release; do not edit by hand.
class Accel < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/mesutoezdil/accel"
  version "0.0.25-main.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.25-main.1/accel-darwin-arm64"
      sha256 "4da77ad095f9814aa2d7a45d2a0ef307c75c0e3ee91ac07a28ccb93df091b978"
    end
    on_intel do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.25-main.1/accel-darwin-amd64"
      sha256 "793560831ac51021d6d66b2dce1390c97135e57c1e220f143325a933e951ce66"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.25-main.1/accel-linux-arm64"
      sha256 "3fd40edaa3d039eb4dd049f980834c5982d71df422e21fec0a2191c4e07d20ba"
    end
    on_intel do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.25-main.1/accel-linux-amd64"
      sha256 "18daf282b9abcc76673916383774f44649450c2deb9cd61dd1137b6276c6becd"
    end
  end

  def install
    binary = Dir["accel-*"].first
    chmod 0755, binary
    bin.install binary => "accel"
    generate_completions_from_executable(bin/"accel", "--completion")
    (man1/"accel.1").write Utils.safe_popen_read(bin/"accel", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/accel --version")
    assert_match "accel", shell_output("#{bin}/accel --demo --once")
  end
end
