# Generated by scripts/update.sh from the v0.0.32-main.1 release; do not edit by hand.
class Accel < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/mesutoezdil/accel"
  version "0.0.32-main.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.32-main.1/accel-darwin-arm64"
      sha256 "b8f5f07a724f8acd1b1324efdcf1e628b625e9c5635229ddf7dee43ad9361e11"
    end
    on_intel do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.32-main.1/accel-darwin-amd64"
      sha256 "90f27847df4828754e166e12fd523f3c12308f03cb2ebc0ec18504e7ca568e46"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.32-main.1/accel-linux-arm64"
      sha256 "dd21cc6106d53bafb0b9ac80a7a06451df54822cc36f7188ddcd88da3929febe"
    end
    on_intel do
      url "https://github.com/mesutoezdil/accel/releases/download/v0.0.32-main.1/accel-linux-amd64"
      sha256 "dd1595943a93687621a39cc3d40c9bd468260a5baf602a4f0ff657df52708e09"
    end
  end

  def install
    binary = Dir["accel-*"].first
    chmod 0755, binary
    bin.install binary => "accel"
    generate_completions_from_executable(bin/"accel", "--completion")
    (man1/"accel.1").write Utils.safe_popen_read(bin/"accel", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/accel --version")
    assert_match "accel", shell_output("#{bin}/accel --demo --once")
  end
end
