# Generated by scripts/update.sh from the v0.0.35-main.1 release; do not edit by hand.
class Siltide < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/mesutoezdil/siltide"
  version "0.0.35-main.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.35-main.1/siltide-darwin-arm64"
      sha256 "b8e4c0d2129fa95a041f6cc110e508c7a8781743f44c7b15011af10dbc507f27"
    end
    on_intel do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.35-main.1/siltide-darwin-amd64"
      sha256 "e4da014cdad6caa8800c98a0b48f81bd72110094d0b90b63123ae7dda3486e3a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.35-main.1/siltide-linux-arm64"
      sha256 "90a44ff00ce0600e62e8f007c7de58ce784462b019ad9a185172ca0ffef6a8bd"
    end
    on_intel do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.35-main.1/siltide-linux-amd64"
      sha256 "0e55d8b0576b9809789cd822fa00ece1ffd98ce04431b0380451bc1056b9a1ed"
    end
  end

  def install
    binary = Dir["siltide-*"].first
    chmod 0755, binary
    bin.install binary => "siltide"
    generate_completions_from_executable(bin/"siltide", "--completion")
    (man1/"siltide.1").write Utils.safe_popen_read(bin/"siltide", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siltide --version")
    assert_match "siltide", shell_output("#{bin}/siltide --demo --once")
  end
end
