# Generated by scripts/update.sh from the v0.0.41-main.3 release; do not edit by hand.
class Siltide < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/mesutoezdil/siltide"
  version "0.0.41-main.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.41-main.3/siltide-darwin-arm64"
      sha256 "9e15e0f0df6a8677d7cdd0ebbb3715c90fd815e1b804ab598560619b44df9d2e"
    end
    on_intel do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.41-main.3/siltide-darwin-amd64"
      sha256 "7c4330ebb724f4989d2ce41f67de1f51a5a1c81ccd63c9caeea3eb503874ad38"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.41-main.3/siltide-linux-arm64"
      sha256 "3a6193bc62fe31cb8c7ba7f3ef692ede9b73b2e9a56f6a813d79019cf81d9f11"
    end
    on_intel do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.41-main.3/siltide-linux-amd64"
      sha256 "44ce658c2194951c4f9d269ac8bf3b99db30aa0472bf3adf4fbcbe9f6d2bb6d0"
    end
  end

  def install
    binary = Dir["siltide-*"].first
    chmod 0755, binary
    bin.install binary => "siltide"
    generate_completions_from_executable(bin/"siltide", "--completion")
    (man1/"siltide.1").write Utils.safe_popen_read(bin/"siltide", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siltide --version")
    assert_match "siltide", shell_output("#{bin}/siltide --demo --once")
  end
end
