# Generated by scripts/update.sh from the v0.0.48-main.1 release; do not edit by hand.
class Siltide < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/mesutoezdil/siltide"
  version "0.0.48-main.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.48-main.1/siltide-darwin-arm64"
      sha256 "19c3e84a07cdba60dec3ceaa8dba3bcd2a2629da40d3ae9a9ca1ea9881a7ed75"
    end
    on_intel do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.48-main.1/siltide-darwin-amd64"
      sha256 "cc042a82cd906ef8bada0fdc1fb5f0920380cb89571f0388c9baba46c66b8e33"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.48-main.1/siltide-linux-arm64"
      sha256 "20511f2701856ec6a8998e8583fe46a6e8a409c11d211beeaa893381004997be"
    end
    on_intel do
      url "https://github.com/mesutoezdil/siltide/releases/download/v0.0.48-main.1/siltide-linux-amd64"
      sha256 "9d7f44438ca098e604b5157b754b54fe8b64edc8fdf256d195e2447e7ba4661f"
    end
  end

  def install
    binary = Dir["siltide-*"].first
    chmod 0755, binary
    bin.install binary => "siltide"
    generate_completions_from_executable(bin/"siltide", "--completion")
    (man1/"siltide.1").write Utils.safe_popen_read(bin/"siltide", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/siltide --version")
    assert_match "siltide", shell_output("#{bin}/siltide --demo --once")
  end
end
