#!/bin/sh
# Renders Formula/accel.rb from the newest accel release: a stable release
# when one exists, otherwise the newest pre-release from main.
set -eu
repo=mesutoezdil/accel
tag=$(gh api "repos/$repo/releases" --jq '[.[] | select(.draft | not) | select(.prerelease | not)][0].tag_name // empty')
[ -n "$tag" ] || tag=$(gh api "repos/$repo/releases" --jq '[.[] | select(.draft | not)][0].tag_name')
version=${tag#v}
sums=$(gh release download "$tag" -R "$repo" -p checksums.txt -O -)
sha() { printf '%s\n' "$sums" | awk -v f="accel-$1" '$2 == f { print $1 }'; }
cat > Formula/accel.rb <<RUBY
# Generated by scripts/update.sh from the $tag release; do not edit by hand.
class Accel < Formula
  desc "Terminal monitor for GPUs, NPUs, and other AI accelerators"
  homepage "https://github.com/$repo"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/$repo/releases/download/$tag/accel-darwin-arm64"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "https://github.com/$repo/releases/download/$tag/accel-darwin-amd64"
      sha256 "$(sha darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/$repo/releases/download/$tag/accel-linux-arm64"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "https://github.com/$repo/releases/download/$tag/accel-linux-amd64"
      sha256 "$(sha linux-amd64)"
    end
  end

  def install
    binary = Dir["accel-*"].first
    chmod 0755, binary
    bin.install binary => "accel"
    generate_completions_from_executable(bin/"accel", "--completion")
    (man1/"accel.1").write Utils.safe_popen_read(bin/"accel", "--man")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/accel --version")
    assert_match "accel", shell_output("#{bin}/accel --demo --once")
  end
end
RUBY
echo "rendered $tag"
